root: true
env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-recommended
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
plugins:
  - vue
rules: {}
