env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
overrides: []
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - .vue
  project:
    - ./tsconfig.json
plugins:
  - vue
rules: {
}